# Generated by Django 4.1.3 on 2022-12-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "s_id",
                    models.IntegerField(
                        max_length=4, primary_key=True, serialize=False
                    ),
                ),
                ("s_name", models.CharField(max_length=100)),
                ("s_class", models.IntegerField()),
                ("s_fa", models.CharField(max_length=100)),
                ("s_marks", models.IntegerField()),
            ],
        ),
    ]
